---
version: 1
sources:
  - name: census_source
    schema: public_raw
    database: iNat
    loader: shp2pgsql
    tables:
      - name: counties_shp
        description: "raw US County mappings with geometry"
        columns:
        - name: geoid
          data_type: int
          tests:
            - unique
            - not_null
        - name: countyfp
          data_type: varchar(4)
          tests:
            - not_null
        - name: statefp
          data_type: varchar(4)
          tests:
            - not_null
