---
version: 1
sources:
  - name: census
    schema: public_raw
    database: iNat
    loader: shp2pgsql
    tables:
      - name: counties_20m_shp
        description: "raw US County mappings with geometry. 1:20,000,000 resolution"
        columns:
        - name: geoid
          data_type: int
          tests:
            - unique
            - not_null
        - name: countyfp
          data_type: varchar(4)
          tests:
            - not_null
        - name: statefp
          data_type: varchar(4)
          tests:
            - not_null

  - name: gbif
    schema: public_raw
    database: iNat
    loader: dask
    tables:
      - name: raw_obs
        description: "Raw Research Grade observations from GBIF API "
        columns:
        - name: gbifID
          data_type: bigint
          constraints:
            - type: primary_key
        - name: taxonKey
          quote: true
          data_type: bigint
          tests:
            - not_null

  - name: gbif
    schema: public_raw
    database: iNat
    loader: psql-cli
    tables:
      - name: gbif_species_match_service
        description: "Outputs from Book species matched with gbif species/match api v1"
        columns:
        - name: gbifID
          data_type: bigint
          constraints:
            - type: primary_key
        - name: taxonKey
          quote: true
          data_type: bigint
          tests:
            - not_null

  - name: census
    schema: public_raw
    database: iNat
    loader: shp2pgsql
    tables:
      - name: counties_5m_shp
        description: "raw US County mappings with geometry. At a 1:5,000,000 resolution"
        columns:
        - name: geoid
          data_type: int
          tests:
            - unique
            - not_null
        - name: countyfp
          data_type: varchar(4)
          tests:
            - not_null
        - name: statefp
          data_type: varchar(4)
          tests:
            - not_null
