---
version: 2
sources:

  - name: gbif
    schema: public_raw
    database: iNat
    loader: dask
    tables:
      - name: raw_obs
        description: "Raw Research Grade observations from GBIF API "
        columns:
        - name: gbifID
          data_type: bigint
          constraints:
            - type: primary_key
        - name: taxonKey
          quote: true
          data_type: bigint
          tests:
            - not_null

  - name: gbif
    schema: public_raw
    database: iNat
    loader: dbt-seed
    tables:
      - name: gbif_species_match_service
        description: "Outputs from Book species matched with gbif species/match api v1"
        columns:
        - name: usageKey
          description: "Taxon Key used in GBIF backbone. Due to historical reasons, some species have multiple distinct usageKeys"
          quote: true
          data_type: bigint
          constraints:
            - type: primary_key

  - name: gbif
    schema: public_raw
    database: iNat
    loader: dbt-seed
    tables:
      - name: gbif_species_unknown_matchback
        description: "Species that were matched from referncing species that were in raw_obs but not in gbif_species_match_service"
        columns:
        - name: usageKey
          description: "Taxon Key used in GBIF backbone. Due to historical reasons, some species have multiple distinct usageKeys"
          quote: true
          data_type: bigint
          constraints:
            - type: primary_key

  - name: census
    schema: public_raw
    database: iNat
    loader: shp2pgsql
    tables:
      - name: counties_5m_shp
        description: "raw US County mappings with geometry. At a 1:5,000,000 resolution"
        columns:
        - name: geoid
          data_type: int
          tests:
            - unique
            - not_null
        - name: countyfp
          data_type: varchar(4)
          tests:
            - not_null
        - name: statefp
          data_type: varchar(4)
          tests:
            - not_null

  - name: census
    schema: public_raw
    database: iNat
    loader: shp2pgsql
    tables:
      - name: counties_20m_shp
        description: "raw US County mappings with geometry. 1:20,000,000 resolution"
        columns:
        - name: geoid
          data_type: int
          tests:
            - unique
            - not_null
        - name: countyfp
          data_type: varchar(4)
          tests:
            - not_null
        - name: statefp
          data_type: varchar(4)
          tests:
            - not_null

  - name: qgis
    schema: public_raw
    database: iNat
    loader: shp2pgsql
    tables:
      - name: filtered_and_clipped_worldgrid_ersi24034
        description: "Grid output from QGIS where each grid is of size 1600mx1600m using counties_5m resolution. Grids that overlap county lines are removed."
