
# Goals
- Extract Scientific Name
- Extract food use

# Basic detect document text
- Add recursive over entire book_images folder
- Could be best to run over images once
    - Save each page as .json
        - file_name
        - Blocks
            - BlockType
            - text (lines and words seperated by '\n')

```{python}
import boto3
import os

client = boto3.client('textract')

response = client.detect_document_text(
    Document={'S3Object': {'Bucket': os.environ['AWS_BUCKET'], 'Name': 'book_images/000001-a.tif'}}
)

for item in response['Blocks']:
    if item['BlockType'] == 'LINE':
        print(item['Text'])
```

# Saving Single Extracted text to new bucket (from one .tif)
```{python}
import boto3
import json
import os

# s3_tif_file='' # from pagnator object

json_name =  '000001-a.tif'.split('.')[0] +'.json' # '000001-a.tif' will come from client pagnator

# json_data = extract_text_from_file(s3_tif_file)
s3_client = boto3.client('s3')

s3_client.put_object(Body=bytes(json.dumps(json_data).encode('UTF-8')),
                     Bucket=os.environ['AWS_BUCKET'],
                     Key=f'book_json/{json_name}',
                     ContentType='application/json')

```


# What pattern can we use to extract food use?
- assist of llm?
## Option 1 - raw text
- get text between FOOD USE and COMMENTS
- use llm to describe what parts are edible
What to do if does not appear on frame?


Checking Block Types

```{python}
from collections import defaultdict

response['Blocks'][0].keys()

unique_type = defaultdict()
for block in response['Blocks']:
    btype = block['BlockType']
    if btype in unique_type:
        unique_type[btype] += 1
    else:
        unique_type[btype] = 1

print(unique_type)
```

# Option 1 Trial
- we can remove the iteration over blocks and simply pass in lines? Nope.

```{python}
def option1(response):
    food_use_lines = []
    food_use_flag = False
    for item in response['Blocks']:
        if item['BlockType'] == 'LINE':
            if food_use_flag:
                food_use_lines.append(item['Text'])
            elif 'FOOD USE' in item['Text']:
                food_use_flag=True
                food_use_lines.append(item['Text'])
            elif 'COMMENTS' in item['Text']:
                food_use_flag=False
            else:
                continue

    # Below checks if list is empty
    if food_use_lines:
        print("Food use found")
        return food_use_lines
    else:
        print("No food use found")
        return food_use_lines
```


```{python}
food_use_lines = option1(response)
food_use_lines = ' '.join(food_use_lines)
print(food_use_lines)
```


# Extracting Scientific Name
QUICK (QUICK CHECK, QUICK ID)
DESCRIPTION

family (there is no general way - but above may capture the most)

- Maybe some use of numbers here
- Use challenging examples of multiple speciues on the same page


```{python}
for item in response['Blocks']:
    if item['BlockType'] == 'LINE':
        print(item['Text'])
```
