---
version: 1

models:
  - name: observations
    columns:
      - name: gbifid
        data_type: bigint
        constraints:
          - type: primary_key
      - name: state_fips
        data_type: varchar(2)
        tests:
          - not_null
      - name: county_fips
        data_type: varchar(4)
        tests:
          - not_null
