---
version: 2

models:
  - name: fct_observations
    columns:
      - name: gbifid
        data_type: bigint
        constraints:
          - type: primary_key
      - name: taxon_key
        data_type: bigint
        constraints:
          - type: foreign_key
            to: ref('dim_species')
            to_columns: [taxon_key]

  - name: dim_species
    columns:
      - name: taxon_key
        data_type: bigint
        constraints:
          - type: primary_key
      - name: scientific_name
        data_type: varchar(128)
        tests:
          - not_null
