---
version: 1

# Indexes created in model file
models:
  - name: counties
    config:
      materialized: table
    columns:
      - name: geoid
        data_type: varchar(5)
        constraints:
          - type: primary_key
      - name: state_fips
        data_type: varchar(2)
      - name: county_fips
        data_type: varchar(4)
        tests:
          - not_null
      - name: county_name
        data_type: varchar(24)
      - name: centroid
        data_type: geography
        tests:
          - not_null
      - name: geom
        data_type: geography
