edible_map = {'stems':'stem',
'fronds':'leaves',
'fiddleheads':'fiddleheads',
'rhizomes':'root',
'root':'root',
'hearts':'heart',
'shoots':'shoots',
'palm hearts':'heart',
'berries':'fruit',
'fruits':'fruit',
'pads':'leaves',
'flower petals':'flower',
'seeds':'seeds',
'young shoots':'shoots',
'greens':'leaves,shoots,stem',
'young leaves':'leaves',
'leaves':'leaves',
'leaves (tea)':'leaves',
'inner bark':'cambium',
'cambium':'cambium',
'needles (tea)':'needles',
'pollen':'pollen',
'bark':'bark',
'immature seed':'immature seed',
'branch tips':'tips',
'nuts':'nuts',
'immature fruits (pickled)':'immature fruit',
'sap (syrup)':'sap',
'immature nuts (pickle)':'immature seed',
'acorns':'nuts',
'hips':'flower',
'oranges':'fruit',
'fruit':'fruit',
'pulp':'fruit',
'apples':'fruit',
'peels(oil)':'peel',
'nut':'nuts',
'inner cambium':'cambium',
'cherries':'fruit',
'roots':'root',
'flowers':'flower',
'newly formed young pods':'immature fruit',
'immature seeds':'immature seeds',
'nuts (coffee)':'nuts',
'seeds (flour)':'seeds',
'fruit (pulp)':'fruit',
'buds':'buds',
'twigs (tea)':'tips',
'bark (tea)':'bark',
'sap (syrup)sap (syrup)':'sap',
'unrip fruit':'fruit',
'flower':'fruit',
'flower buds':'buds',
'tips':'tips',
'tendrils':'tips',
'grapes':'fruit',
'tubers':'root',
'young greens':'leaves,stem,shoots',
'rootstocks':'root',
'tender young leaves':'leaves',
'rhizome tips':'root',
'stem bases':'stem',
'young corms':'root',
'shoot tips':'shoots',
'stem':'stem',
'rhizome':'root',
'lateral shoots':'shoots',
'green flower':'immature flower',
'heart':'heart',
'tender flower shoot':'shoot',
'immature flower bud clusters':'buds',
'immature flower':'immature flower',
'young hearts of leaf cluster bases':'stems',
'young spikes of immature flower buds':'immature buds',
'tender greens':'leaves,stems,shoots',
'stem tips':'tips',
'corms':'root',
'rootstock':'root',
'shoot':'shoots',
'seed' :'seeds',
'bulbs':'root',
'scapes':'stem',
'green pods':'immature fruit',
'tender leaves':'leaves',
'flower stalk':'stem',
'tender green parts':'leaves,shoots,stems',
'young stems':'stems',
'stalks':'stems',
'bulb':'root',
'youngest leaves':'leaves',
'flowerbuds':'flowerbuds',
'peduncles':'stems',
'flower stalks':'stems',
'':'UNKNOWN',
'taproot':'root',
'petioles':'leaves',
'bulblets':'root',
'young petioles':'stems',
'young stem':'stems',
'tuber':'root',
'leafy tops':'leaves',
'flower bud clusters':'buds',
'midribs':'stems',
'midrib':'stems',
'flower heart':'heart',
'tender shoots':'shoots',
'young spring leaves':'leaves',
'tender tops':'leaves',
'tender stems':'stems',
'immature fruits':'fruit',
'peeled shoots':'shoots',
'sap':'sap',
'seedpods':'seeds',
'tops':'leaves',
'tender tips':'tips',
'fruts':'fruits',
'spring shoots':'shoots',
'sheets':'shoots',
'taproots':'root',
'tender leafy stems':'stems',
'young stems and greens':'stems,leaves,shoots',
'young stalks':'shoots',
'roots (fall)':'roots',
'youngest greens':'leaves,shoots,stems',
'young pods':'immature seeds',
'plump green seeds':'immature seeds',
'tender stem tips':'tips',
'ripe seeds':'seeds',
'underground beans':'beans',
'beans':'beans',
'immature pods':'immature seeds',
'mature seeds':'seeds',
'leafy tips':'tips',
'galls':'galls',
'vine tips':'tips',
'ripe fruit':'fruit',
'mints':'leaves,stems',
'tenders':'leaves,stems,stalks',
'flowerheads':'flowers',
'leafy greens':'leaves',
'pith':'pith',
'new leaves':'leaves',
'immature seedpods':'immature seedpods',
'unripe seeds':'immature seeds',
'young leafy tips':'tips',
'youngest shoots':'shoots',
'leavy stem tips':'tips',
'ripe fruits':'fruits',
'tender leafy tips':'tips',
'pods':'immature fruits',
'stemp tips':'stem'}

edible_map_granular = {
'stems':'STEMS_SHOOTS',
'fronds':'LEAVES_GREENS',
'fiddleheads':'SPECIALIZED',
'rhizomes':'ROOTS_UNDERGROUND',
'root':'ROOTS_UNDERGROUND',
'hearts':'SPECIALIZED',
'shoots':'STEMS_SHOOTS',
'palm hearts':'SPECIALIZED',
'berries':'FRUITS',
'fruits':'FRUITS',
'pads':'PODS',
'flower petals':'FLOWERS_BUDS',
'seeds':'SEEDS_NUTS',
'young shoots':'STEMS_SHOOTS',
'greens':'LEAVES_GREENS',
'young leaves':'LEAVES_GREENS',
'leaves':'LEAVES_GREENS',
'leaves (tea)':'LEAVES_GREENS',
'inner bark':'BARK_SAP',
'cambium':'BARK_SAP',
'needles (tea)':'LEAVES_GREENS',
'pollen':'FLOWERS_BUDS',
'bark':'BARK_SAP',
'immature seed':'SEEDS_NUTS',
'branch tips':'STEMS_SHOOTS',
'nuts':'SEEDS_NUTS',
'immature fruits (pickled)':'FRUITS',
'sap (syrup)':'BARK_SAP',
'immature nuts (pickle)':'SEEDS_NUTS',
'acorns':'SEEDS_NUTS',
'hips':'FRUITS',
'oranges':'FRUITS',
'fruit':'FRUITS',
'pulp':'FRUITS',
'apples':'FRUITS',
'peels(oil)':'FRUITS',
'nut':'SEEDS_NUTS',
'inner cambium':'BARK_SAP',
'cherries':'FRUITS',
'roots':'ROOTS_UNDERGROUND',
'flowers':'FLOWERS_BUDS',
'newly formed young pods':'PODS',
'immature seeds':'SEEDS_NUTS',
'nuts (coffee)':'SEEDS_NUTS',
'seeds (flour)':'SEEDS_NUTS',
'fruit (pulp)':'FRUITS',
'buds':'FLOWERS_BUDS',
'twigs (tea)':'STEMS_SHOOTS',
'bark (tea)':'BARK_SAP',
'sap (syrup)sap (syrup)':'BARK_SAP',
'unrip fruit':'FRUITS',
'flower':'FLOWERS_BUDS',
'flower buds':'FLOWERS_BUDS',
'tips':'STEMS_SHOOTS',
'tendrils':'STEMS_SHOOTS',
'grapes':'FRUITS',
'tubers':'ROOTS_UNDERGROUND',
'young greens':'LEAVES_GREENS',
'rootstocks':'ROOTS_UNDERGROUND',
'tender young leaves':'LEAVES_GREENS',
'rhizome tips':'ROOTS_UNDERGROUND',
'stem bases':'STEMS_SHOOTS',
'young corms':'ROOTS_UNDERGROUND',
'shoot tips':'STEMS_SHOOTS',
'stem':'STEMS_SHOOTS',
'rhizome':'ROOTS_UNDERGROUND',
'lateral shoots':'STEMS_SHOOTS',
'green flower':'FLOWERS_BUDS',
'heart':'SPECIALIZED',
'tender flower shoot':'FLOWERS_BUDS',
'immature flower bud clusters':'FLOWERS_BUDS',
'immature flower':'FLOWERS_BUDS',
'young hearts of leaf cluster bases':'SPECIALIZED',
'young spikes of immature flower buds':'FLOWERS_BUDS',
'tender greens':'LEAVES_GREENS',
'stem tips':'STEMS_SHOOTS',
'corms':'ROOTS_UNDERGROUND',
'rootstock':'ROOTS_UNDERGROUND',
'shoot':'STEMS_SHOOTS',
'seed':'SEEDS_NUTS',
'bulbs':'ROOTS_UNDERGROUND',
'scapes':'STEMS_SHOOTS',
'green pods':'PODS',
'tender leaves':'LEAVES_GREENS',
'flower stalk':'STEMS_SHOOTS',
'tender green parts':'LEAVES_GREENS',
'young stems':'STEMS_SHOOTS',
'stalks':'STEMS_SHOOTS',
'bulb':'ROOTS_UNDERGROUND',
'youngest leaves':'LEAVES_GREENS',
'flowerbuds':'FLOWERS_BUDS',
'peduncles':'STEMS_SHOOTS',
'flower stalks':'STEMS_SHOOTS',
'':'NEEDS_CLEANING',
'taproot':'ROOTS_UNDERGROUND',
'petioles':'STEMS_SHOOTS',
'bulblets':'ROOTS_UNDERGROUND',
'young petioles':'STEMS_SHOOTS',
'young stem':'STEMS_SHOOTS',
'tuber':'ROOTS_UNDERGROUND',
'leafy tops':'LEAVES_GREENS',
'flower bud clusters':'FLOWERS_BUDS',
'midribs':'STEMS_SHOOTS',
'midrib':'STEMS_SHOOTS',
'flower heart':'FLOWERS_BUDS',
'tender shoots':'STEMS_SHOOTS',
'young spring leaves':'LEAVES_GREENS',
'tender tops':'STEMS_SHOOTS',
'tender stems':'STEMS_SHOOTS',
'immature fruits':'FRUITS',
'peeled shoots':'STEMS_SHOOTS',
'sap':'BARK_SAP',
'seedpods':'PODS',
'tops':'STEMS_SHOOTS',
'tender tips':'STEMS_SHOOTS',
'fruts':'FRUITS',
'spring shoots':'STEMS_SHOOTS',
'sheets':'LEAVES_GREENS',
'taproots':'ROOTS_UNDERGROUND',
'tender leafy stems':'STEMS_SHOOTS',
'young stems and greens':'STEMS_SHOOTS',
'young stalks':'STEMS_SHOOTS',
'roots (fall)':'ROOTS_UNDERGROUND',
'youngest greens':'LEAVES_GREENS',
'young pods':'PODS',
'plump green seeds':'SEEDS_NUTS',
'tender stem tips':'STEMS_SHOOTS',
'ripe seeds':'SEEDS_NUTS',
'underground beans':'SEEDS_NUTS',
'beans':'SEEDS_NUTS',
'immature pods':'PODS',
'mature seeds':'SEEDS_NUTS',
'leafy tips':'LEAVES_GREENS',
'galls':'SPECIALIZED',
'vine tips':'STEMS_SHOOTS',
'ripe fruit':'FRUITS',
'mints':'LEAVES_GREENS',
'tenders':'STEMS_SHOOTS',
'flowerheads':'FLOWERS_BUDS',
'leafy greens':'LEAVES_GREENS',
'pith':'SPECIALIZED',
'new leaves':'LEAVES_GREENS',
'immature seedpods':'PODS',
'unripe seeds':'SEEDS_NUTS',
'young leafy tips':'LEAVES_GREENS',
'youngest shoots':'STEMS_SHOOTS',
'leavy stem tips':'STEMS_SHOOTS',
'ripe fruits':'FRUITS',
'tender leafy tips':'LEAVES_GREENS',
'pods':'PODS',
'stemp tips':'STEMS_SHOOTS'
}
