edible_map = {'leafstalks':'stalk',
              'stalk':'stalk',
              'flowers':'flower',
              'florets':'flower',
              'male flowers':'flower',
              'flower heads':'flower',
              'green pine needles':'needle',
              'needles':'needle',
              'buds':'bud',
              'unopened flower buds':'bud',
              'flower buds':'bud',
              'flower pods':'bud',
              'seeds':'seed',
              'nuts':'nut',
              'fruits':'fruit',
              'berries':'fruit',
              'shoots':'shoot',
              'leaves from the stem':'leave',
              'leaves':'leave',
              'seed heads':'seed',
              'green seeds':'seed',
              'seedpods':'seed',
              'seed head':'seed',
              'fruits':'fruit',
              'blooms':'flower',
              'immature flower stalks':'stalk',
              'flower stalk':'stalk',
              'root crown':'root',
              'tubers':'root',
              'root':'root',
              'corms':'root',
              'rhizomes':'root',
              'first-year taproot':'root',
              'bulbs':'root',
              'bulb':'root',
              'hips':'flower',
              'roots':'root',
              'inner bark':'bark',
              'stalks':'stalk',
              'stems':'stem',
              'twigs':'twigs',
              'pads':'leave',
              'tips':'tips',
              'pollen':'pollen',
              'bark':'bark',
              'sap':'sap',
              'newly formed  pods':'fruit',
              'primocane shoots':'shoot',
              'immature seedcones':'seedcones',
              'branch tips':'tips',
              'hazlenuts':'nuts',
              'oranges':'fruit',
              'apples':'fruit',
              'cherries':'fruit',
              'pods':'fruit',
              'beans':'fruit',
              'cambium':'bark',
              'buf-faloberries':'fruit',
              'succulentsaity leaves':'leave',
              'dried fruit':'fruit',
              'starch':'root',
              'tender  leaves':'leave',
              'lateral rhizomes':'root',
              'cores':'heart',
              'green to with grain or you vegetables':'seed',
              'peduncles':'stalk',
              'greens':'leave',
              'leaf shoots':'shoot',
              'kernels':'seed',
              'rootstock':'root',
              'scapes':'stalk',
              'green pods':'fruit',
              'stem_tips':'tips',
              'whitish heart':'heart',
              'flowerbuds':'bud',
              'ripe grains':'seed',
              'flowerstalks':'stalk',
              'immature spikes':'stalk',
              'ripe ponds':'fruit',
              'peduncles':'stalk',
              'berries':'fruit',
              'tendergrowth':'tips',
              'flower stalk shoots':'stalk',
              'peduncles':'stalk',
              'above-ground portions':'above-ground-portions',
              'stemtips':'tips',
              'growth':'tips',
              'tuber':'root',
              'lower 2/3 of the root':'root',
              'tender leaves':'leave',
              'spring leaves':'leave',
              'flower bud clusters':'bud',
              'tendorshoots':'shoot',
              'peeled shoots':'shoot',
              'peeled shops':'shoot',
              'parts':'leave',
              'tender':'tips',
              'seed ponds':'seed',
              'taproot':'root',
              'tap root':'root',
              'underground beans':'fruit',
              'youngest greens':'leave',
              'ripe fruit':'fruit',
              'immature pods':'fruit',
              'mature seeds':'seed',
              'shoots/greens':'leave',
              'leafytips':'tips',
              'leafy greens':'leave',
              'palm hearts':'heart',
              'youngleafy tips':'tips',
              'tender green parts':'tips',
              'hazelnuts':'nut',
              'stem teps':'tips',
              'ripe pods':'fruit',
              'digged bulbs':'root',
              'petioles':'leave',
              'strawberries':'fruit',
              'bulblets':'root',
              'tinytubers':'root',
              'peeled stalks':'stalk',
              'whiter lower part of the stalk':'stalk',
              'leafytops':'leave',
              'flowerbud clusters':'bud',
              'bases':'stem',
              'tops':'tips',
              'tendershoots':'shoot',
              'tender shoots':'shoot',
              'basal leaves':'leave',
              'immature fruits':'fruit',
              'tender stem tips':'tips',
              'tender  stems':'stem',
              'seed pods':'seed',
              'taproots':'root',
              'tender shoots':'shoot',
              'flowerheads':'flower',
              'youngpods':'fruit',
              'tender stem tips':'tips',
              'tender greens':'leave',
              'tender leafy tips':'tips',
              'leafy tops':'leave',
              'vine tips':'tips',
              'spring growth':'leave',
              'aerial tubers':'root',
              'sprounts':'stem',
              'new leaves':'leave',
              'tender leafy tops':'tips',
              'growing tips':'tips',
              'leafy tops':'leave',
              'youngest shoots':'shoot',
              'leafy tips':'tips',
              'leaf blades':'leave',
              'new parts':'tips',
              'storage organ':'root',
              'flower stalk shoot':'shoot',
              'petals':'flower',
              'mints':'leave',
              'husks':'seed',
              'stem tips':'tips',
              'tip':'tips',
              'sprouts':'stem',
              'buds':'bud',
              'acorns':'nut',
              '':'?'
           }
