edible_map = {'leafstalks':'stalk',
              'stalk':'stalk',
              'flowers':'flower',
              'florets':'flower',
              'male flowers':'flower',
              'flower heads':'flower',
              'green pine needles':'needle',
              'needles':'needle',
              'buds':'bud',
              'unopened flower buds':'bud',
              'flower buds':'bud',
              'flower pods':'bud',
              'seeds':'seed',
              'nuts':'nut',
              'fruits':'fruit',
              'shoots':'shoot',
              'leaves from the stem':'leave',
              'leaves':'leave',
              'seed heads':'seed',
              'green seeds':'seed',
              'seedpods':'seed',
              'seed head':'seed',
              'fruits':'fruit',
              'blooms':'flower',
              'immature flower stalks':'stalk',
              'flower stalk':'stalk',
              'root crown':'root',
              'tubers':'root',
              'root':'root',
              'corms':'root',
              'rhizomes':'root',
              'first-year taproot':'root',
              'bulbs':'root',
              'bulb':'root',
              'hips':'flower',
              'roots':'root',
              'inner bark':'bark',
              'stalks':'stalk',
              'stems':'stem',
              'twigs':'twig',
              '':'?'
           }
