---
version: 1

models:
  - name: stg_county_centroids
    columns:
      - name: geoid
        data_type: varchar(5)
        constraints:
          - type: primary_key
      - name: state_fips
        data_type: varchar(2)
        tests:
          - not_null
      - name: county_fips
        data_type: varchar(3)
        tests:
          - not_null
      - name: centroid
        tests:
          - not_null

  - name: stg_species_info
    columns:
      - name: taxon_key
        data_type: bigint
        constraints:
          - type: primary_key
      - name: scientific_name
        data_type: varchar(32)
        tests:
          - not_null
      - name: taxon_rank
        data_type: varchar(8)
        tests:
          - not_null
      - name: edibles
        data_type: varchar(128)
        tests:
          - not_null

# See model for indexes, materialization strategy
  - name: stg_observations
    config:
      materialized: table
    +indexes:
      - columns: ['geo_loc']
        type: gist
    columns:
      - name: gbifID
        data_type: bigint
        constraints:
          - type: primary_key
      - name: geo_loc
        data_type: geometry
        tests:
          - not_null
      - name: taxon_key
        data_type: bigint
        tests:
          - not_null
