-- Edible genus in
with edible_genus as (
    Select *
    from {{ref('stg_species_info')}}
    where taxon_rank = 'GENUS'
),

-- Appending edibles. Note not all records were able to be matched
edibles_appended as (
    Select 
    unk.usageKey as taxon_key,
    unk.canonicalname as scientific_name,
    unk.first_of_canonical,
    unk."rank" as taxon_rank,
    unk.family,
    unk.family_key,
    unk.genus,
    unk.genus_key,
    unk.species,
    unk.species_key,
    eg.edibles,
    eg.stems_shoots,
    eg.leaves_greens,
    eg.specialized,
    eg.roots,
    eg.fruits,
    eg.pods,
    eg.flowers_buds,
    eg.seeds_nuts,
    eg.bark_sap,
    eg.e_stem,
    eg.e_leaves,
    eg.e_fiddleheads,
    eg.e_root,
    eg.e_heart,
    eg.e_shoots,
    eg.e_fruit,
    eg.e_flower,
    eg.e_seeds,
    eg.e_cambium,
    eg.e_needles,
    eg.e_pollen,
    eg.e_bark,
    eg.e_immature_seed,
    eg.e_tips,
    eg.e_nuts,
    eg.e_immature_fruit,
    eg.e_sap,
    eg.e_peel,
    eg.e_immature_seeds,
    eg.e_buds,
    eg.e_immature_flower,
    eg.e_shoot,
    eg.e_stems,
    eg.e_immature_buds,
    eg.e_flowerbuds,
    eg.e_fruits,
    eg.e_roots,
    eg.e_beans,
    eg.e_galls,
    eg.e_stalks,
    eg.e_flowers,
    eg.e_pith,
    eg.e_immature_seedpods,
    eg.e_immature_fruits,
    eg.book_name
    from {{ref('gbif_species_unknown_matchback')}} unk
    INNER JOIN edible_genus eg
    ON unk.genus_key = eg.genus_key
),

unioned as (
    Select * 
    from edibles_appended
    UNION ALL
    Select 
    taxon_key,
    scientific_name,
    first_of_canonical,
    taxon_rank,
    family,
    family_key,
    genus,
    genus_key,
    species,
    species_key,
    edibles,
    stems_shoots,
    leaves_greens,
    specialized,
    roots,
    fruits,
    pods,
    flowers_buds,
    seeds_nuts,
    bark_sap,
    e_stem,
    e_leaves,
    e_fiddleheads,
    e_root,
    e_heart,
    e_shoots,
    e_fruit,
    e_flower,
    e_seeds,
    e_cambium,
    e_needles,
    e_pollen,
    e_bark,
    e_immature_seed,
    e_tips,
    e_nuts,
    e_immature_fruit,
    e_sap,
    e_peel,
    e_immature_seeds,
    e_buds,
    e_immature_flower,
    e_shoot,
    e_stems,
    e_immature_buds,
    e_flowerbuds,
    e_fruits,
    e_roots,
    e_beans,
    e_galls,
    e_stalks,
    e_flowers,
    e_pith,
    e_immature_seedpods,
    e_immature_fruits,
    book_name
    from {{ ref('stg_species_info')}}
)

Select * from unioned

